name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Container file for amd64 and arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t cpython_autoconf:test .
