name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Dockerfile for amd64 and arm64
    strategy:
      fail-fast: false
      matrix:
        autoconf_version: ["2.69", "2.71", "2.72"]
    runs-on: ubuntu-latest
    env:
      TAG: autoconf:${{ matrix.autoconf_version }}-${{ github.run_id }}
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: AUTOCONF_VERSION=${{ matrix.autoconf_version }}
          load: true
          tags: ${{ env.TAG }}
      - name: Test
        run: docker run --rm $TAG autoconf --version | grep ${{ matrix.autoconf_version }}
