# This workflow will perform a test whenever there
# is some change in code done to ensure that the changes
# are not buggy and we are getting the desired output.
name: Build and Push Manifest
on:
  release:
    types: [published]

env:
  IMAGE_NAME: cpython_autoconf
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: dongheena

jobs:
  push-quay:
    name: Build and push manifest
    runs-on: ubuntu-20.04

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Install latest podman and qemu
        run: |
          sudo apt-get -y install podman
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.event.release.tag_name }}
          archs: amd64, arm64
          containerfiles: |
            ./Dockerfile

      # Push the image manifest to Quay.io (Image Registry)
      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        id: push-to-quay
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
