# This workflow will perform a test whenever there
# is some change in code done to ensure that the changes
# are not buggy and we are getting the desired output.
name: Build and Push Manifest
on:
  release:
    types: [published]

jobs:
  push-quay:
    name: Build and push manifest
    runs-on: ubuntu-20.04

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Install latest podman and qemu
        run: |
          sudo apt-get -y install podman
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@main
        with:
          image: cpython_autoconf
          tags: ${{ github.event.release.tag_name }}
          archs: amd64, arm64
          containerfiles: |
            ./Dockerfile

      - name: Login To GHCR
        uses: docker/login-action@v1
        with:
          registery: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}

      - name: Push To GHCR
        run: |
          docker push ghcr.io/corona10/${{ steps.build_image.outputs.image }}/${{ steps.build_image.outputs.tags }}
